//WEATHER DASHBOARD

//WHEN THE USER SEARCHES FOR A CITY 5 DAY WEATHER FORECAST IS PRESENTED
//THE CITY IS ADDED TO THE SEARCH BAR
//CURRENT WAETHER CONDITIONS INCLUDE (CITY NAME,DATE,ICON REPRESENTATION,TEMPERATURE, HUMIDITY, WIND SPEED)
//WHEN THE USER CLICKS ON THE PREVIOUS SEARCH THEY ARE PRESENTED WITH THE CURRENT AND FUTURE CONDITIONS